### ISSUE TITLE
email verification functionality

### ISSUE THREAD

**Issue by kasandrop** [mk-5/gdx-fireapp#10]
Atm it is impossible to send  an email to user to verify  an email address.

**Comment by mk-5** [comment]
Thanks for reporting. 

Ok, as far as this moment API does not contains this functionality. 
It will be add in next release! 1.8.1 (very soon)

**Comment by mk-5** [comment]
The new version (1.8.1) is available. Example with email verification is here: https://github.com/mk-5/gdx-fireapp/wiki/Examples#user-menage
