### ISSUE TITLE
Default FirebaseApp is not initialized in this process com.mygdx.game. Make sure to call FirebaseApp.initializeApp(Context) first.

### ISSUE THREAD

**Issue by PandlaS** [mk-5/gdx-fireapp#22]
**Describe the bug**
I am getting this message: Default FirebaseApp is not initialized in this process com.mygdx.game. Make sure to call FirebaseApp.initializeApp(Context) first.

**To Reproduce**

Json File: android/google-services.json

@Override
	public void create () {
		batch = new SpriteBatch();
		img = new Texture("badlogic.jpg");
		**GdxFIRApp.inst().configure();**
		**GdxFIRDatabase.inst()
					.inReference("/user")
					.push()
					.setValue(new User("Bob", "bob@bob.com"));**

	}

**Expected behavior**

**Platform (please check one of the following):**
 - [ ] Android

**Smartphone (please complete the following information only if platform is Android or iOS):**

**Comment by PandlaS** [comment]
it was missing 'google play' from class path. Thanks

**Comment by mk-5** [comment]
no problem, if any other problems occur or you need some new feature to be covered - please let me know :)
