### ISSUE TITLE
onDataChange called receiving warning

### ISSUE THREAD

**Issue by hermanghub** [mk-5/gdx-fireapp#3]
I've tried the readValue method and managed to retrieved the records on Firebase realtime database.
Then I try to implement onDataChange with (MyClass.class, new DataChangeListener<MyClass>()) and override the onChange method.

When running my app, I saw below in Logcat:
W/ClassMapper: No setter/field for xxxx found on class ...MyClass

and onChange is not called.

Please find the definition of MyClass as below:
public class MyClass {
    public String initials;
    public String dateTime;
    public String remarks;

    public MyClass() {}
    public MyClass(String initials, String dateTime, String remarks) {
        this.initials = initials;
        this.dateTime = dateTime;
        this.remarks = remarks;
    }

    public String getInitials() {
        return initials;
    }

    public void setInitials(String initials) {
        this.initials = initials;
    }

    public String getDateTime() {
        return dateTime;
    }

    public void setDateTime(String dateTime) {
        this.dateTime = dateTime;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}

What have I done wrong or missing? 

Also, what I really want to do is to maintain some sort of hall of fame records in Firebase database and display. How should I code to retrieve the 10 latest records from the database? or I need to wait for the next release for filtering/query feature?

Thanks in advance.
Herman

**Comment by mk-5** [comment]
Hi!

Unfortunately at this point is no way to get limited number of rows. You can try limit records by structure. 
Yes, support for filtering/querying will be here in next release - but at this moment i don't know when it will be.

Can you put some sample code, how do you call GdxFireapp API?

**Comment by hermangh** [comment]
Please refer to the sample code I mentioned in #4. Thanks.

**Comment by mk-5** [comment]
`W/ClassMapper: No setter/field for xxxx found on class ...` is throwing when there are some fields inside DB which your POJO does not cover by setters. Look here: https://firebase.google.com/support/guides/firebase-android#update_your_java_model_objects . 
GdxFireapp Api ignore unknown fields on ios, but i still working on it at android platform. 
I'll let you know here when I'm done - very soon

**Comment by hermanghub** [comment]
Thanks for the reference link. I'll study it. Thanks.

**Comment by hermanghub** [comment]
Recently used v1.3.1. The warning is gone on both Android and ios! Thanks anyway!
