### ISSUE TITLE
GWT doesn't work

### ISSUE THREAD

**Issue by mk-5** [mk-5/gdx-fireapp#36]
**Describe the bug**
GWT firebase integration is broken

**To Reproduce**
Run any of GdxFIR*** method on html.

**Expected behavior**
It should work the same way as for the other platforms.

**Platform (please check one of the following):**
 - [ ] Android
 - [ ] iOS
 - [X] Web

**Comment by mk-5** [comment]
Hi @jeffgamedev 

There is a new version 2.1.7. Many small fixes for GWT have been provided there
I'm not sure if EVERYTHING is working, I had some problems to run database API. 

Basically, GWT backend should start working again 🤞 feel free to check the latest version, and report any issue here :)

**Comment by jeffgamedev** [comment]
Hi MK5!

I'm hoping I have time to check this out tonight! Thanks again! I'll let
you know my results.

Best,

Jeff

**Comment by jeffgamedev** [comment]
Great news! My GWT Built with Fireapp!!

Now I must implement. I will let you know my progress!

Thanks again, my friend!

Jeff
