### ISSUE TITLE
Feature request for roboVM ios backend

### ISSUE THREAD

**Issue by Daniel-Donev** [mk-5/gdx-fireapp#40]
Hi guys,

Are you planning to realize soon a version that supports roboVM ios backend, because ios-moe is removed from the latest libgdx version and is no longer supported?

Thanks!

**Comment by mk-5** [comment]
Hi! 

👍 definitively, it's a must-be. I think it will be implemented in the next release. Keep track this issue

**Comment by kaloyanhlebarov** [comment]
Upvote! I`m currently trying to release my game and this is the only issue I have on iOS that is stopping me. I`ll be very thankful if you can tell me roughly when do you plan to integrate that feature?

**Comment by mk-5** [comment]
I'm currently working on some game, and I also will need this RoboVM back-end ;) I'm planning to get this at some point of October. I hope that works for you

**Comment by mk-5** [comment]
Unfortunately, I had a little delay, because of corona situation. No health issue, but I'm waiting for a new Mac, and my shipment is delayed. 

Stay tuned, it's closer and closer with each day. For sure it has high-prio for me right now

**Comment by Daniel-Donev** [comment]
Thank you very much!

**Comment by mk-5** [comment]
Good news, the new version 3.0.1 with RoboVM backend, and libgdx 1.9.12 is available to use. 

I've updated the iOS quick start as well: https://github.com/mk-5/gdx-fireapp/wiki/iOS-Guide

**Comment by Daniel-Donev** [comment]
Hi, it seems that there are some problems with the integration.
First we had to add <forceLinkClasses><pattern>pl.mk5.gdx.fireapp.ios.**</pattern></forceLinkClasses> in robovm.xml to resolve some minor errors.

We get this error on authentication: pl.mk5.gdx.fireapp.ios.auth.GoogleAuthProvider$GIDSignDelegate cannot be cast to org.robovm.objc.ObjCObject

We are using this code for the Auth process. On Android there is no problem, but on iOS roboVM it fails.
`GdxFIRAuth.inst().google().signIn().then(new Consumer<GdxFirebaseUser>() {
            @Override
            public void accept(GdxFirebaseUser user) {
                game.user = user;
            }
        }).fail(new BiConsumer<String, Throwable>() {
            @Override
            public void accept(String s, Throwable throwable) {
                game.userSkipLogin = true;
            }
        });`
        
Is there another way we should be authenticating for iOS as there is no available description in the WIKI for roboVM?
https://github.com/mk-5/gdx-fireapp/wiki/Google-Sign-in

Thank you!

**Comment by mk-5** [comment]
Hello @Daniel-Donev 

I'll test this Google signIn. No no, you are doing everything right. It looks like something went wrong with multi-os-engine -> robovm porting. 

I'll check it

**Comment by Daniel-Donev** [comment]
Thanks! 
I will wait for your response.

**Comment by mk-5** [comment]
@Daniel-Donev pls check latest version 3.0.2. Should work now

**Comment by Daniel-Donev** [comment]
Hi, thanks it's working now. :)

**Comment by mk-5** [comment]
🎆🎆🎆

the next step is to integrate more SignIn providers.
