### ISSUE TITLE
Can't seem to use OrderByChild to order results

### ISSUE THREAD

**Issue by tiagoalexs** [mk-5/gdx-fireapp#41]
**Describe the bug**
Hello, i've been trying for the past couple of hours to try and add a leaderboard system to my university project, but i can't seem to order the results by the user score.

The "highScore" variables are stored as doubles and returned through the method below as Long variables.

![studio64_Tl7VKoONRk](https://user-images.githubusercontent.com/54414138/90997147-a6004480-e5b8-11ea-8af8-d4cfdc409ce5.png)

I tried using only List instead of List < User > and the result is the same.

![studio64_VhoSYhoJkF](https://user-images.githubusercontent.com/54414138/90996726-83b9f700-e5b7-11ea-9774-65d8dfa5ab0f.png)

![chrome_yK0fV5K3R5](https://user-images.githubusercontent.com/54414138/90996747-903e4f80-e5b7-11ea-9faf-1aba33b7fe87.png)

![Screenshot_2020-08-24-03-12-06-447_com mygdx endlessrunner](https://user-images.githubusercontent.com/54414138/90996807-bc59d080-e5b7-11ea-827f-ff30d1d2f45a.jpg)

The results should appear either in ascending or descending order for both leaderboards
Don't really know what i'm missing here

**Platform (please check one of the following):**
 - [X] Android
 - [ ] iOS
 - [ ] Web

**Comment by mk-5** [comment]
Hi @tiagoalexs 

I need to check, I will let you know!

**Comment by mk-5** [comment]
@tiagoalexs fix will be ready soon. Please look forward to a new version

https://github.com/mk-5/gdx-fireapp/pull/42

**Comment by mk-5** [comment]
Hi @tiagoalexs 

can you grab&check the latest version 2.1.8? I've added e2e test for a case like your case https://github.com/mk-5/gdx-fireapp/blob/master/e2e/core/src/pl/mk5/gdx/fireapp/e2e/tests/DatabaseOrderByChildTest.java  and it works. 

I hope that fix will work for you as well -> if no, please let me know.

**Comment by tiagoalexs** [comment]
Hi @mk-5 
I've been testing it out and everything seems to be working alright.
Thanks for the fix!

**Comment by mk-5** [comment]
cool 👍
