### ISSUE TITLE
External manager class

### ISSUE THREAD

**Issue by BeppeMarnell** [mk-5/gdx-fireapp#43]
Hi, I have few years of experience with libGDX, I have used it a lot for university stuff. I was looking at various databases implementations in libGDX. This one is really good! Compliments and thank you for keeping the project updated!

I have a main class (the classic libGDX initial class) and a manager class where I put all the Firebase methods (as shown in the picture). 
After few tests, nothing works when using this class. 
Right now I am testing this in Android, calling the methods when a button is pressed.

I may be doing something wrong, but the only way in which I can make it work is to blindly copy paste the example methods in  the main class. 
Is this how it is supposed to be or I am missing something ?

This is the firebase manager class, just to give you an idea.
<img width="519" alt="Screenshot 2020-09-02 at 12 35 22" src="https://user-images.githubusercontent.com/35118227/91971015-d4002a00-ed18-11ea-97c8-61a1ca5dc443.png">

**Comment by BeppeMarnell** [comment]
Sorry for the post, I've managed to understand the problem. There is something to be with the "final" variables. So, no issue with the library.

**Comment by mk-5** [comment]
@BeppeMarnell no problem. Feel free to create an issue at any time
