### ISSUE TITLE
Firebase crashlytics support

### ISSUE THREAD

**Issue by Daniel-Donev** [mk-5/gdx-fireapp#44]
Hi guys,

From 15.10.2020 old version of fabric crashlytics is deprecated.
I try updating my project to android X and the new firebase crashlytics  SDK but FireApp is not supporting it. :(

Do you have any plans to support it and when?

**Comment by mk-5** [comment]
Hello @Daniel-Donev ,

sure 👍  it shouldn't be so tough / but currently, I need to focus on RoboVM IOS backend -> Multi-Os engine isn't supported by the latest libgdx version. 


I will check how tough would it be, maybe I can bring it to FireApp quickly -> please monitor this issue ;)

**Comment by mk-5** [comment]
Hello again @Daniel-Donev  

Good news ;) there are really minor changes between fabric and a new one -> I will try to bring it to gdx-fireapp today

**Comment by mk-5** [comment]
@Daniel-Donev it will be available with 2.2.1 version 🍻

**Comment by mk-5** [comment]
@Daniel-Donev stay tuned. Something goes wrong with a deployment. I will check it today. Anyway -> the version 2.2.1 will contain Crashlytics support

**Comment by mk-5** [comment]
@Daniel-Donev please check version 2.2.1

**Comment by Daniel-Donev** [comment]
I`ve tested it and everything works fine. 

Thank you very much for the great work!
