### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by burf2000** [mk-5/gdx-fireapp#5]
Hi there, this looks great, are you still working on it?  I have made a simple online game where I just want to pole position and update where stuff is, have a scoreboard etc.

Do you think I could use this?  I used Parse in the past and written my own backend?

**Comment by mk-5** [comment]
Hi!

Yes, i will work on it for sure. The next feature will be google/facebook authorization, but if is something that you need NOW - please create issue with feature description - I will take care of it for sure.
If you found some bug or problem, please create issue also.

The API do not had full Firebase API coverage - but I plan to add them one by one. I use this API in some comercial apps now - so sure, you can use it.

**Comment by kasandrop** [comment]
Is it possible to arrange some kind of consultancy .I would like you to explain me some of  your code from gdx-fireapp. I am not really an expert but really would like to understand some difficult parts. I am happy to reward you that time spent with me. I am Polish as well so consultancy in Polish . Please let me know if it is possible to arrange. Kasandrop@gmail.com

**Comment by mk-5** [comment]
Sure! Feel free to ask me at git@mk5.pl (you can write emails in polish ;) )

**Comment by kasandrop** [comment]
Czesc.
Bylbym zainteresowany 1h na razie takiego spotkania konsultacyjnego na
skype w celu zebys mi dokladnie umowil twoj napisany kod w javie. Api dla
database i authorization. Te dwa moduly. Interesuje mnie szczegolnie i
tylko  co sie dzieje po kolei od momentu polaczenia z database do momentu
otrzymania danych przez funkcjje callback. Z wykorzystaniem debuggera
staralem sie przesledzic kolejne wywolywania ale sie gubie ....
Ja jestem samoukiem java to moje hobby. Sam sie wyedukowalem mysle ze na
sredni poziom z ksiazek i roznych kursow internetowych. Ostatnio
interesowalem  sie frameworkiem libgdx i po pewnym czasie odkrylem
technologie  zwiazana z  firebase . I tak trafilem na twoje api. Prosze o
ustalenie stawki za godzine konsultacji. Zaplace z gory. Na razie 1h
zobacze jak to sie uda. Nigdy z nikim nie rozmawialem na temat javy.

Bardzo prosze o odpowiedz. Dostepny dzis jestem wtorek i we srode
wieczorem. Czy znajdzie pan troche czasu?

**Comment by PandlaS** [comment]
hi @mk-5 ,
Is it possible to support FireStore (database). Right now, it seems only RealTimeDatabase is supported, if you can just add the support for Firestore as well that will help a lot. 

Thanks.

**Comment by mk-5** [comment]
@PandlaS yes sure, it will be the next feature then :) 

Currently, I'm working on RemoteConfig API, so FireStore will be the next
