### ISSUE TITLE
Support for multiple realtime databases

### ISSUE THREAD

**Issue by edosam** [mk-5/gdx-fireapp#51]
Problem:
There is a real need to connect to multiple (different) realtime databases for bigger projects. For example, there is one database for Android users and one for iOS users. 

Solution:
It would be nice if there is a method like this:
**GdxFIRDatabase.inst(String dbUrl);**

Firebase doc:
https://firebase.google.com/docs/database/usage/sharding

**Comment by mk-5** [comment]
@edosam hello there!

good point. It should be easy to modify. I will pick it up

**Comment by mk-5** [comment]
@edosam hello again 

so, the feature is ready to be merged and deploy. There is one problem: jcenter is dead. 

I need to find some alternative. Maven-central deployments are pain in the ass

**Comment by mk-5** [comment]
@edosam okay, I decided to use mavenCentral for now. 

The new version 3.1.0 is deployed. It should be available in maven-central search within ~2 hours. 
Please let me know if that works for you. 

The multiple-database feature works exactly as you proposed. There is a new method:

`GdxFIRDatabase.inst(String dbUrl)`

Wiki page with example: https://github.com/mk-5/gdx-fireapp/wiki/Database-sharding

**Comment by mk-5** [comment]
@edosam I'm closing this issue. Feel free to re-open it in case of any issues with multi-databases solution

**Comment by edosam** [comment]
Hello @mk-5 
Thank you for implementing this feature.
It's working correctly on Android device, but app is still connecting to base database on iOS.
Is there some other configuration required for iOS? Or it isn't just implemented for iOS?

**Comment by mk-5** [comment]
@edosam it should work on ios as well. I need to check

**Comment by mk-5** [comment]
@edosam  I checked, and it looks good 🤔  

could you send me an info about which DB action is causing this problem? 

by the way, in order to use different database for iOS/Android, you can also add different DATABASE_URL in your `GoogleService-info.plist` like this:

```
	<key>DATABASE_URL</key>
	<string>https://diffrent-url-for-ios.firebaseio.com</string>
```
