### ISSUE TITLE
fatal error: 'FirebaseCore/FirebaseCore.h' file not found

### ISSUE THREAD

**Issue by burf2000** [mk-5/gdx-fireapp#6]
Using the current Firebase it does not seem to contain a Framework file, just the source?

**Comment by burf2000** [comment]
You need to use a version of firebase 4.x

**Comment by mk-5** [comment]
Yes, you are right. Current version (1.3.1) was build with Firebase SDK 3.*.

I should do some update for the latest version. I will do that, please wait for some info here
