### ISSUE TITLE
onChildChange function doesn't work

### ISSUE THREAD

**Issue by wangdong20** [mk-5/gdx-fireapp#61]
**Describe the bug**
I tried to use onChildChange function to observe ChildEvent.Added event with wanted datatype Map::class.java(Kotlin). When DB child added, but no luck.

**To Reproduce**
1. Write code: `ref.inReference("users/${it.userInfo.uid}").onChildChange(Map::class.java, ChildEventType.ADDED).then(Consumer<Map<String, Any>>{// TODO})`
2. Add child by Firebase-Function
3. Child added event doesn't trigger

**Expected behavior**
onChildChange observe child added event with Map.class wanted datatype doesn't work when child added.

**Platform (please check one of the following):**
 - [**] Android
 - [ ] iOS
 - [ ] Web

**Smartphone (please complete the following information only if platform is Android or iOS):**
 - Device: Android
 - OS: 4.4.2

**Comment by mk-5** [comment]
@wangdong20 I think you are listening on the wrong path. According to firebase documentation:

```
child_added is triggered once for each existing child and then again every time a new child is added to the specified path.
```

You should listen on `inReference("users").onChildChange(List.class, ChildEventType.ADDED)`. I know that you already switched yourself to official android SDK so I'm going to close the issue. Pls feel free to re-open it :)
