### ISSUE TITLE
Crashlytics info. 

### ISSUE THREAD

**Issue by Ashraf-Al-Odat** [mk-5/gdx-fireapp#7]
Hi, I'm using this project in my game and it's a really great tool thnx for building it.

But now I'm planning to add a crash report mechanism. So i check google to see there service and they said that Firebase Crash Reports will no longer be accessible after September 8, 2018.

So my question is, what is implemented the new Crashlytics or the old crash report?

**Comment by mk-5** [comment]
Hello! 

Thank's for reporting. Yes, I know about that, the Crashlytics support will be add in the next release and it will replace Firebase Crash.
Watch the repo, it will be release very soon.

**Comment by mk-5** [comment]
Crashlytics was added in version 1.6.1. For more info go to this Wiki page: [Crashlytics](https://github.com/mk-5/gdx-fireapp/wiki/Crashlytics)
