### ISSUE TITLE
Password reset function

### ISSUE THREAD

**Issue by kasandrop** [mk-5/gdx-fireapp#9]
Password reset function is missing. Firebase has got this function:
FirebaseAuth.getInstance().sendPasswordResetEmail(email@email.pl)
Serious login mechanism  needs that  functionality..

**Comment by mk-5** [comment]
Thanks for reporting. 

Yes, you are right. It will be add in next release! 1.8.1

**Comment by mk-5** [comment]
The new version (1.8.1) is available. Example with sendPasswordResetEmail is here: https://github.com/mk-5/gdx-fireapp/wiki/Examples#user-menage
